### ISSUE TITLE
zoomrec login not working anymore

### ISSUE THREAD

**Issue by den1k** [kastldratza/zoomrec#35]
**Describe the bug**
I tried logging in to a few different accounts, remote and locally but it always fails with the error `1132`

**To Reproduce**
Try logging in. If it works for you I'll be happy.
**Expected behavior**
Login succeeds without error.

**Screenshots**
![CleanShot 2022-04-22 at 11 15 34](https://user-images.githubusercontent.com/4651810/164743827-3508244f-26b7-4cd1-ae0d-d7f3815cf091.png)

**Desktop (please complete the following information):**
 - OS: MacOS + Docker | Ubuntu + Docker

**Comment by uriafranko** [comment]
receiving that error also,

have you tried rebuilding the image so the zoom client will update to the newest one?

**Comment by den1k** [comment]
yes tried a lot of things including changing the ubuntu version, changing the name of the user etc. all to no avail. I think this might be a kind of bot detection by zoom

**Comment by ash2811** [comment]
I have been getting similar error since 21st April.
Getting same error on (1) Macbook pro (M1) and (2) ubuntu virtual machine on cloud. The code was working on both environments till 20th April.
<img width="1000" alt="zoom_error_1132" src="https://user-images.githubusercontent.com/104342876/165033041-7f89b9a9-09fa-4a3d-a406-bc894e53c057.png">

**Comment by uriafranko** [comment]
After a bit of research on the Zoom forum community.

The error 1132, is for deactivated accounts.

I'm guessing they "banned" or something the IP or whatever.

**Comment by den1k** [comment]
I can still log in with the same account on a different computer

**Comment by ToasteR1032** [comment]
Can confirm, same issue here.
